const fetch = require('node-fetch'); // Si no lo tienes, haz 'npm install node-fetch'

const url = 'https://v3.football.api-sports.io/leagues?name=argentina';

fetch(url, {
  method: 'GET',
  headers: {
    'x-apisports-key': '85bb624fed12b70d65b6d6a5a5dc28c',
    'x-rapidapi-host': 'v3.football.api-sports.io'
  }
})
.then(res => res.json())
.then(json => console.log(JSON.stringify(json, null, 2)))
.catch(err => console.error('error:' + err));